import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "../globals.css";
import Navbar from "../components/Navbar";
import CompanyLogos from "../components/CompanyLogos";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FlySha - Website Bokking Ticket",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { session, user } = await getUser();

  if (session && user.role === "CUSTOMER") {
    redirect("/");
  }

  return (
    <html lang="en">
      <body
        className={`${inter.className} text-white font-poppins bg-flysha-black`}
      >
        <section
          id="Signup"
          className="bg-[url('/assets/images/background/airplane.png')] bg-no-repeat bg-cover bg-left-top -z-10 min-h-screen"
        >
          <div className="Header-content bg-gradient-to-r from-[#080318] to-[rgba(8,3,24,0)] z=0 min-h-screen">
            <Navbar />
            <div className="flex flex-col justify-between min-h-[calc(100vh-78px)]">
              {children}
              <CompanyLogos />
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
